# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-26 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_kategoriler'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='kategoriler',
            field=models.ManyToManyField(related_name='blog', to='blog.Kategori'),
        ),
    ]
