# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-26 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190526_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(help_text='Kapak fotoğrafı yükleyiniz', null=True, upload_to='', verbose_name='Resim'),
        ),
    ]
