# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-27 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190527_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=1000, null=True, verbose_name='İçerik Giriniz'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default/wall.png', help_text='Kapak fotoğrafı yükleyiniz', null=True, upload_to='blog', verbose_name='Resim'),
        ),
    ]
