# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-27 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190527_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='yayin_taslak',
            field=models.CharField(choices=[((None, 'Seçiniz'), ('yayin', 'YAYIN')), ('taslak', 'TASLAK')], max_length=6, null=True),
        ),
    ]
