# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-29 12:49
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190527_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=1000, null=True, verbose_name='İçerik Giriniz'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='yayin_taslak',
            field=models.CharField(choices=[(None, 'Seçiniz'), ('yayin', 'YAYIN'), ('taslak', 'TASLAK')], max_length=6, null=True),
        ),
    ]
