# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-29 14:59
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190529_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=20, null=True, verbose_name='İsim')),
                ('soyisim', models.CharField(blank=True, max_length=20, null=True, verbose_name='Soyisim')),
                ('email', models.EmailField(blank=True, help_text='Bu alan zorunlu.', max_length=254, null=True, verbose_name='Email')),
                ('icerik', ckeditor.fields.RichTextField(help_text='Yorum yazınız.', max_length=1000, null=True, verbose_name='Yorum')),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
            ],
        ),
    ]
